[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.8.8"
indexmap = { version = "2.2.4", features = ["serde"] }
anyhow = "1.0.79"
